# Generated by Django 5.1.6 on 2026-02-14 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('experience', models.IntegerField()),
                ('language', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(upload_to='priest_photos/')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='priest_certificates/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='priest_id_proofs/')),
                ('services', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='priest_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
