# Generated by Django 5.1.6 on 2026-02-17 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(help_text='Service slug from services_data', max_length=100)),
                ('booking_date', models.DateField()),
                ('slot_type', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('custom', 'Custom Time')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('devotee_name', models.CharField(max_length=255)),
                ('devotee_phone', models.CharField(max_length=15)),
                ('devotee_address', models.TextField()),
                ('special_requests', models.TextField(blank=True, help_text='Any special requirements or requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('priest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.priestprofile')),
            ],
            options={
                'ordering': ['-booking_date', '-start_time'],
                'indexes': [models.Index(fields=['priest', 'booking_date', 'status'], name='core_bookin_priest__e33e68_idx'), models.Index(fields=['devotee', 'status'], name='core_bookin_devotee_2f1b96_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriestAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_available', models.BooleanField(default=False)),
                ('morning_start', models.TimeField(blank=True, help_text='Morning slot start time (e.g., 06:00)', null=True)),
                ('morning_end', models.TimeField(blank=True, help_text='Morning slot end time (e.g., 12:00)', null=True)),
                ('afternoon_available', models.BooleanField(default=False)),
                ('afternoon_start', models.TimeField(blank=True, help_text='Afternoon slot start time (e.g., 12:00)', null=True)),
                ('afternoon_end', models.TimeField(blank=True, help_text='Afternoon slot end time (e.g., 18:00)', null=True)),
                ('evening_available', models.BooleanField(default=False)),
                ('evening_start', models.TimeField(blank=True, help_text='Evening slot start time (e.g., 18:00)', null=True)),
                ('evening_end', models.TimeField(blank=True, help_text='Evening slot end time (e.g., 21:00)', null=True)),
                ('custom_slots', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, help_text='Any special notes or instructions for this date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.priestprofile')),
            ],
            options={
                'verbose_name_plural': 'Priest Availabilities',
                'ordering': ['date'],
                'unique_together': {('priest', 'date')},
            },
        ),
    ]
