# Generated by Django 5.2.11 on 2026-02-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_priestprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priestprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='priest_photos/'),
        ),
    ]
