# Generated by Django 5.2.11 on 2026-02-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_priestprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priestprofile',
            name='language',
            field=models.JSONField(default=list),
        ),
    ]
