# Generated by Django 5.1.6 on 2026-02-21 05:27

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_priestprofile_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='priestprofile',
            name='mobile',
            field=models.CharField(max_length=10, validators=[core.models.validate_mobile]),
        ),
        migrations.CreateModel(
            name='DevoteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=10, validators=[core.models.validate_mobile])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devotee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
