# Generated by Django 5.1.6 on 2026-02-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_priestprofile_mobile_devoteeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gothram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='nakshatram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
