# Generated by Django 5.1.6 on 2026-02-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking_gothram_booking_nakshatram'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='devotee_completed',
            field=models.BooleanField(default=False, help_text='Set when devotee confirms the puja is done'),
        ),
        migrations.AddField(
            model_name='booking',
            name='priest_completed',
            field=models.BooleanField(default=False, help_text='Set when priest marks the puja as done'),
        ),
    ]
