# Generated by Django 5.2.11 on 2026-02-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_booking_devotee_completed_booking_priest_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='devotee_started',
            field=models.BooleanField(default=False, help_text='Set when devotee confirms the puja has started'),
        ),
        migrations.AddField(
            model_name='booking',
            name='priest_started',
            field=models.BooleanField(default=False, help_text='Set when priest marks the puja as started'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
