# Generated by Django 5.2.11 on 2026-02-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_booking_devotee_started_booking_priest_started_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priestprofile',
            name='fullname',
        ),
        migrations.AddField(
            model_name='priestprofile',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='priestprofile',
            name='gothram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='priestprofile',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='priestprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='priestprofile',
            name='qualification_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='priestprofile',
            name='traditional_methods',
            field=models.BooleanField(default=False),
        ),
    ]
