# Generated by Django 5.1.6 on 2026-02-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_priestprofile_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priestprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='priestprofile',
            name='gothram',
        ),
        migrations.RemoveField(
            model_name='priestprofile',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='priestprofile',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='priestprofile',
            name='qualification_location',
        ),
        migrations.RemoveField(
            model_name='priestprofile',
            name='traditional_methods',
        ),
        migrations.AddField(
            model_name='priestprofile',
            name='fullname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
