# Generated by Django 5.1.6 on 2026-02-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_priestprofile_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priestprofile',
            name='can_perform_rituals',
            field=models.BooleanField(default=True, help_text='Can perform as per scriptures?'),
        ),
        migrations.AddField(
            model_name='priestprofile',
            name='gothram',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='priestprofile',
            name='qualification',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='priestprofile',
            name='qualification_place',
            field=models.TextField(default=''),
        ),
    ]
