# Generated by Django 5.1.6 on 2026-03-02 09:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_priestprofile_can_perform_rituals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoteeprofile',
            name='address',
            field=models.TextField(default='', validators=[core.models.validate_hyderabad]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='devotee_address',
            field=models.TextField(validators=[core.models.validate_hyderabad]),
        ),
        migrations.AlterField(
            model_name='priestprofile',
            name='location',
            field=models.TextField(validators=[core.models.validate_hyderabad]),
        ),
    ]
