# Generated by Django 5.1.6 on 2026-03-02 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_devoteeprofile_address_alter_booking_devotee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='secondary_priest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_bookings', to='core.priestprofile'),
        ),
        migrations.AddField(
            model_name='booking',
            name='secondary_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, null=True),
        ),
    ]
