# Generated by Django 5.1.6 on 2026-03-03 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_booking_secondary_priest_booking_secondary_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='secondary_priest',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='secondary_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_priest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_bookings', to='core.priestprofile'),
        ),
        migrations.AddField(
            model_name='booking',
            name='extra_priest_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['additional_priest', 'booking_date', 'status'], name='core_bookin_additio_faf621_idx'),
        ),
    ]
