# Generated by Django 5.1.6 on 2026-03-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_booking_secondary_priest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='devotee_completed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='devotee_started',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='priest_completed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='priest_started',
        ),
    ]
