# Generated by Django 5.1.6 on 2026-03-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_booking_devotee_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='devotee_completed',
            field=models.BooleanField(default=False, help_text='Set when devotee confirms the puja is done'),
        ),
        migrations.AddField(
            model_name='booking',
            name='devotee_started',
            field=models.BooleanField(default=False, help_text='Set when devotee confirms the puja has started'),
        ),
        migrations.AddField(
            model_name='booking',
            name='priest_completed',
            field=models.BooleanField(default=False, help_text='Set when priest marks the puja as done'),
        ),
        migrations.AddField(
            model_name='booking',
            name='priest_started',
            field=models.BooleanField(default=False, help_text='Set when priest marks the puja as started'),
        ),
    ]
