# Generated by Django 5.1.6 on 2026-03-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_booking_devotee_completed_booking_devotee_started_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='devotee_completed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='devotee_started',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='priest_completed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='priest_started',
        ),
    ]
