# Generated by Django 5.1.6 on 2026-03-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lead_priest_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
