# Generated by Django 5.2.11 on 2026-03-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_booking_lead_priest_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='priestprofile',
            name='formal_vedic_training',
            field=models.BooleanField(default=False, help_text='Have you formally undergone Vedic training?'),
        ),
        migrations.AddField(
            model_name='priestprofile',
            name='knows_smaardham',
            field=models.BooleanField(default=False, help_text='Have you know of the Veda called Smaardham?'),
        ),
        migrations.AddField(
            model_name='priestprofile',
            name='organize_scientifically',
            field=models.BooleanField(default=False, help_text='Can you organize the program scientifically?'),
        ),
        migrations.AlterField(
            model_name='priestprofile',
            name='qualification',
            field=models.TextField(default='', help_text='Highest Educational Qualification'),
        ),
        migrations.AlterField(
            model_name='priestprofile',
            name='qualification_place',
            field=models.TextField(default='', help_text='Gurukulam / Vedic Institution'),
        ),
    ]
