# Generated by Django 5.2.11 on 2026-03-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_priestprofile_formal_vedic_training_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Service amount in rupees', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending', 'Pending Confirmation'), ('payment_completed', 'Payment Completed'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('cancelled_by_purohit', 'Cancelled by Purohit')], default='pending', max_length=20),
        ),
    ]
