# Generated by Django 6.0.3 on 2026-03-10 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_puja_bookingfeedback_bookingadditionalpriest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='has_enquiry',
            field=models.BooleanField(default=False, help_text='True if devotee has raised an enquiry'),
        ),
        migrations.CreateModel(
            name='BookingEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry', to='core.booking')),
            ],
            options={
                'verbose_name_plural': 'Booking Enquiries',
            },
        ),
    ]
