# Generated by Django 5.2.11 on 2026-03-10 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_enquirycategory_pujacategory_alter_puja_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puja',
            name='gallery',
        ),
        migrations.AddField(
            model_name='puja',
            name='inclusions',
            field=models.TextField(blank=True, help_text='Enter Seva inclusions, one per line.'),
        ),
        migrations.AlterField(
            model_name='puja',
            name='benefits',
            field=models.TextField(blank=True, help_text='Enter benefits, one per line.'),
        ),
        migrations.AlterField(
            model_name='puja',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pujas/main/'),
        ),
        migrations.CreateModel(
            name='PujaGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pujas/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('puja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.puja')),
            ],
            options={
                'verbose_name': 'Puja Gallery Image',
                'verbose_name_plural': 'Puja Gallery Images',
                'ordering': ['display_order'],
            },
        ),
    ]
