# Generated by Django 5.2.11 on 2026-03-10 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_puja_gallery_puja_inclusions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAboutConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Authentic & Divine', max_length=255)),
                ('subtitle', models.TextField(default='We bring traditional Vedic rituals to your doorstep with utmost devotion.')),
                ('badge_text', models.CharField(default='Why Choose Us', max_length=100)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='home/about/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home About Configuration',
                'verbose_name_plural': 'Home About Configuration',
            },
        ),
        migrations.CreateModel(
            name='HomeHeroConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_gold', models.CharField(default='BRINGING SACRED', max_length=255)),
                ('title_ivory', models.CharField(default='RITUALS TO YOUR HOME', max_length=255)),
                ('subtitle', models.TextField(default='Experience the sanctity of Authentic Vedic Rituals performed by verified Pandits.')),
                ('quote_text', models.CharField(default='Dharmo Rakshati Rakshitah', max_length=255)),
                ('watermark_text', models.CharField(default='ॐ नमः शिवाय', max_length=100)),
                ('hero_bg_1', models.ImageField(blank=True, null=True, upload_to='home/hero/')),
                ('hero_bg_2', models.ImageField(blank=True, null=True, upload_to='home/hero/')),
                ('hero_bg_3', models.ImageField(blank=True, null=True, upload_to='home/hero/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Hero Configuration',
                'verbose_name_plural': 'Home Hero Configuration',
            },
        ),
        migrations.CreateModel(
            name='SankalpPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sankalp Pillar',
                'verbose_name_plural': 'Sankalp Pillars',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SpiritualJourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(help_text='e.g., 01, 02', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='FontAwesome class, e.g., fas fa-hand-holding-heart', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Spiritual Journey Step',
                'verbose_name_plural': 'Spiritual Journey Steps',
                'ordering': ['display_order', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/testimonials/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['display_order', '-date_added'],
            },
        ),
    ]
