# Generated by Django 5.2.11 on 2026-03-10 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_homeaboutconfig_homeheroconfig_sankalppillar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text="The URL path (e.g., '/', '/services/')", max_length=255, unique=True)),
                ('title_tag', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadata',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('booking_new', 'New Booking Request'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('enquiry_new', 'New Enquiry Raised'), ('system_alert', 'System Alert')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriestPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assigned', models.PositiveIntegerField(default=0)),
                ('completed_successful', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='core.priestprofile')),
            ],
        ),
    ]
