# Generated by Django 5.2.12 on 2026-03-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_seometadata_notification_priestperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund'), ('pending', 'Refund Pending'), ('initiated', 'Refund Initiated'), ('completed', 'Refund Completed'), ('failed', 'Refund Failed')], default='none', max_length=20),
        ),
    ]
