# Generated by Django 5.2.12 on 2026-03-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_booking_refund_amount_booking_refund_initiated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='has_enquiry',
            new_name='enquiry_raised',
        ),
        migrations.AddField(
            model_name='booking',
            name='puja_completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when status was set to completed', null=True),
        ),
    ]
